---
- name: First server preparation
  hosts: all
  gather_facts: false
  become: no
  # ignore_errors: true
  vars:
    ssh_key_filename: key
    ssh_key_location_path: /home/natali/ansible
    sshd_config_file: /etc/ssh/sshd_config
    local_user: natali

  tasks:
  - name: generate SHH key "{{ ssh_key_filename }}"
    user:
      name: "{{ local_user }}"
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 4096
      ssh_key_file: "{{ ssh_location_path }}/{{ ssh_key_filename }}"
      force: no
    delegate_to: localhost
    run_once: yes

  - name: add key to remote hosts
    authorized_key:
      key: "{{ lookup('file', ssh_location_path+'/'+ssh_key_filename+'.pub') }}"
      state: present
      user: "{{ ansible_user }}"

  - name: Disable root login
    become: yes
    lineinfile:
      path: "{{ sshd_config_file }}"
      regexp: "^#PermitRootLgin"
      line: "PermitRootLogin no"
    notify: restart sshd

  - name: Enforce SSH key passphrases
    become: yes
    lineinfile:
      path: "{{ sshd_config_file }}"
      regexp: "^#PermitEmtyPasswords"
      line: "PermitEmptyPasswords yes"
    notify: restart sshd

  - name: Disable paasword ssh connection
    become: yes
    lineinfile:
      path: "{{ sshd_config_file }}"
      regexp: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"
    notify: restart sshd

  handlers:
  - name: restart sshd
    become: yes
    service:
      name: sshd
      state: restarted
