---
- name: add user with group
  become: yes
  user:
    name: admin
    groups: sudo
    password: 123
    shell: /bin/bash

- name: generate SSH key 
  user:
    name: "{{ local_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "{{ ssh_key_location_path }}/{{ ssh_key_filename }}"
    force: no
  delegate_to: localhost
  run_once: yes

- name: add key to remote host
  authorized_key:
    key: "{{ lookup('file', ssh_key_location_path+'/'+ssh_key_filename+'.pub') }}"
    state: present
    user: admin

- name: update configuration file
  ansible.builtin.template:
    src: /home/natali/ansible/roles/user_with_keys/templates/sshd_config_copy.j2
    dest: "{{ sshd_config_file }}"
  notify: 
    - restart sshd




